# This configuration has been moved to the root pyproject.toml
# This file is kept for backward compatibility during transition
# All tool configurations (ruff, pytest, etc.) are now managed at the root level

# Legacy configuration - DO NOT ADD NEW CONFIGURATIONS HERE
# Use /pyproject.toml at the repository root instead
