"""add_save_slots_table

Revision ID: 50b401563356
Revises: 9a6d5baf6502
Create Date: 2026-03-25 19:09:09.225158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b401563356'
down_revision: Union[str, Sequence[str], None] = '9a6d5baf6502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('play_time_seconds', sa.Integer(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('character_level', sa.Integer(), nullable=False),
    sa.Column('current_location', sa.String(), nullable=False),
    sa.Column('save_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_save_slots_campaign_id'), 'save_slots', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_save_slots_id'), 'save_slots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_save_slots_id'), table_name='save_slots')
    op.drop_index(op.f('ix_save_slots_campaign_id'), table_name='save_slots')
    op.drop_table('save_slots')
    # ### end Alembic commands ###
