---
name: CI (DEPRECATED)

# This workflow has been deprecated in favor of dedicated test workflows:
# - unit-tests.yml for fast PR feedback 
# - integration-tests.yml for comprehensive testing on main branch
# - e2e-tests.yml for end-to-end testing on main branch
#
# This workflow is kept for legacy compatibility but does minimal work

on:
  # Only run on main pushes for basic health check
  push:
    branches: [main]

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Basic repository health check
      run: |
        echo "✅ Repository structure looks good"
        test -f pyproject.toml
        test -d backend/app
        test -d frontend/src
        echo "✅ All basic files present"
